# -*- coding: utf-8 -*-

# --------------------------------------------------------------------
# The MIT License (MIT)
#
# Copyright (c) 2016 Jonathan Labéjof <jonathan.labejof@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# --------------------------------------------------------------------

"""Schema registry module."""

__all__ = [
    'SchemaRegistry',
    'getbyuuid', 'getbyname', 'register', 'unregister', 'fromcls'
]

from .factory import getschema

#: class attribute for Schema data_type association
__DATA_TYPES__ = '__data_types__'


class SchemaRegistry(object):
    """In charge of register schemas."""

    def __init__(
            self,
            schemas=None, schbyname=None, schbyuuid=None, schbytype=None,
            *args, **kwargs
    ):
        """
        :param list schemas: starting schemas to register.
        :param dict schbyname: schemas by name.
        :param dict schyuid: schemas by uuid.
        :param dict schbytype: schemas by type.
        """

        super(SchemaRegistry, self).__init__(*args, **kwargs)

        self._schbyname = schbyname or {}
        self._schbyuuid = schbyuuid or {}
        self._schbytype = schbytype or {}

        if schemas:
            for schema in schemas:
                self.register(schema)

    def register(self, schema, data_types=None):
        """Register input schema class.

        When registering a schema, all inner schemas are registered as well.

        :param Schema schema: schema to register.
        :param list data_types: python data_types associated to schema when the
            data_type is an instance of the schema.
        :return: old registered schema.
        :rtype: type"""

        result = None

        uuid = schema.uuid

        if uuid in self._schbyuuid:
            result = self._schbyuuid[uuid]

        if result != schema:

            self._schbyuuid[uuid] = schema

            name = schema.name

            schemas = self._schbyname.setdefault(name, set())

            schemas.add(schema)

            for innername, innerschema in schema.schemas():

                if innerschema.uuid not in self._schbyuuid:
                    register(innerschema)

        if data_types is not None:
            for data_type in data_types:
                self._schbytype[data_type] = schema

        return result

    def fromcls(self, cls, force=False):
        """Get the schema able to instanciate object of input class cls.

        :param cls: classes where objects could be generated by a schema.
        :param bool force: if True, create the object schema on the fly if it
            does not exist.
        :return: Schema.
        :rtype: type
        :raises: TypeError if the object is not associated to a registered data
            type."""

        result = None

        if cls in self._schbytype:
            result = self._schbytype[cls]

        else:
            for data_type in self._schbytype:
                if issubclass(cls, data_type):
                    result = self._schbytype[data_type]
                    break

            else:
                if force:
                    result = getschema(cls)

                else:
                    raise TypeError(
                        'object {0} is not associated to a registered schema'.
                        format(cls)
            )

        return result

    def unregister(self, uuid):
        """Unregister a schema registered with input uuid.

        :raises: KeyError if uuid is not already registered."""

        schema = self._schbyuuid.pop(uuid)

        # clean schemas by name
        self._schbyname[schema.name].remove(schema)
        if not self._schbyname[schema.name]:
            del self._schbyname[schema.name]

        # clean schemas by data type
        for data_type in list(self._schbytype):
            _schema = self._schbytype[data_type]
            if _schema == schema:
                del self._schbytype[data_type]

    def getbyuuid(self, uuid):
        """Get a schema by given uuid.

        :param str uuid: schema uuid to retrieve.
        :rtype: Schema
        :raises: KeyError if uuid is not registered already."""

        if uuid not in self._schbyuuid:
            raise KeyError('uuid {0} not registered'.format(uuid))

        return self._schbyuuid[uuid]

    def getbyname(self, name):
        """Get schemas by given name.

        :param str name: schema names to retrieve.
        :rtype: list
        :raises: KeyError if name is not registered already."""

        if name not in self._schbyname:
            raise KeyError('name {0} not registered'.format(name))

        return self._schbyname[name]


_REGISTRY = SchemaRegistry()  #: global Schemaregistry.


def register(schema, data_types=None):
    """Register globally input shema.

    :param b3j0f.schema.Schema: schema to register."""

    return _REGISTRY.register(schema=schema, data_types=data_types)


def fromcls(obj, force=False):
    """Get the schema able to instanciate object of input class cls.

    :param cls: classes where objects could be generated by a schema.
    :param bool force: if True, create the object schema on the fly if it
        does not exist.
    :return: Schema.
    :rtype: type
    :raises: TypeError if the object is not associated to a registered data
        type."""

    return _REGISTRY.fromcls(cls=cls, force=force)


def unregister(uuid):
    """Unregister"""

    return _REGISTRY.unregister(uuid=uuid)


def getbyuuid(uuid):
    """Get globally a schema by given uuid.

    :param str uuid: schema uuid to retrieve.
    :rtype: type
    :raises: KeyError if name is not registered already."""

    return _REGISTRY.getbyuuid(uuid=uuid)


def getbyname(name):
    """Get globally a schema by given name.

    :param str name: schema names to retrieve.
    :rtype: list
    :raises: KeyError if name is not registered already."""

    return _REGISTRY.getbyname(name=name)
